### ISSUE TITLE
Inclusion in official collection?

### ISSUE THREAD

**Issue by AndreaCrotti** [swannodette/clojure-snippets#4]
Hi,
I'm the maintainer of the official snippets collection for yasnippet:
https://github.com/AndreaCrotti/yasnippet-snippets

I wanted to add some clojure snippets to the collection since we don't have any now and I saw your collection is pretty good.

Would you be interested in moving them there?
Or in case you prefer to keep a separate repository would you mind if I import them?
(if you move them of course you will still be the author and you'll be able to contribute as much as you like)
Thanks a lot,
Andrea

**Comment by mordocai** [comment]
I would like to vote in support of these being in the official collection.

**Comment by pybae** [comment]
Has any progress been made?
I too am quite interested in seeing this repository in the official collection.

**Comment by AndreaCrotti** [comment]
Just noticed this was still open, well there are already many clojure related snippets and if anyone wants more they are easy to add, so closing this..
